name: ✅ Test
on:
  push:
defaults:
  run: { shell: bash }
jobs:
  matrix:
    name: 📋 Generate Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Generate Matrix
        id: matrix
        uses: pgxn/matrix-action@v0
        with:
          deprecated: true
          beta: true
          devel: true

  test:
    name: ${{ matrix.pg.emoji }} ${{ matrix.pg.os }}/${{ matrix.pg.arch }} 🐘 v${{ matrix.pg.version }}
    needs: matrix
    runs-on: ${{ matrix.pg.runner }}
    strategy:
      fail-fast: false
      matrix:
        pg: ${{ fromJson(needs.matrix.outputs.matrix) }}
        exclude:
          - { pg: { os: Windows, version: 16 } }
          - { pg: { os: Windows, version: 15 } }
          - { pg: { os: Windows, version: 14 } }
          - { pg: { os: Windows, version: 13 } }
          - { pg: { os: Windows, version: 12 } }
          - { pg: { os: Windows, version: 11 } }
          - { pg: { os: Windows, version: 10 } }
          - { pg: { os: Windows, version: 9.6 } }
          - { pg: { os: Windows, version: 9.5 } }
          - { pg: { os: Windows, version: 9.4 } }
          - { pg: { os: Windows, version: 9.3 } }
    steps:
      - name: Check out the repo
        uses: actions/checkout@v7
      - name: Start Postgres ${{ matrix.pg.version }}
        id: pg
        uses: ./
        with:
          version: ${{ matrix.pg.version }}
      - name: Build
        working-directory: test/pgxs
        run: make -j $(nproc)
      - name: Install
        working-directory: test/pgxs
        run: sudo make install
      - name: Test
        id: test
        working-directory: test/pgxs
        run: make installcheck
      - name: Show Diffs
        if: failure() && steps.test.outcome == 'failure'
        run: find . -name regression.diffs -exec cat {} +
      - name: Upload Diffs
        if: failure() && steps.test.outcome == 'failure'
        uses: actions/upload-artifact@v7
        with:
          name: regression-diffs-${{ matrix.pg.os }}-${{ matrix.pg.arch }}-pg${{ matrix.pg.version }}
          path: |
            test/pgxs/regression.diffs
            test/pgxs/results

  inputs:
    strategy:
      fail-fast: false
      matrix:
        pg: [18]
        os:
          - { img: 🍎, name: macOS  }
          - { img: 🐧, name: Ubuntu }
          - { img: 🪟, name: Windows  }
        opt:
          - { port: 6543, encoding: SQL_ASCII, locale: en_US.UTF-8 }
          - { port: 7743, encoding: EUC_KR,    locale: C,  }
    name: ${{ matrix.os.img }} ${{ matrix.os.name }} ${{ matrix.opt.encoding }}
    runs-on: ${{ matrix.os.name }}-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v7
      - name: Start Postgres ${{ matrix.pg }}
        id: pg
        uses: ./
        with:
          version: ${{ matrix.pg }}
          packages: hugo
          port: ${{ matrix.opt.port }}
          encoding: ${{ matrix.opt.encoding }}
          locale: ${{ matrix.opt.locale }}
      - name: Check stuff
        run: |
          set -e
          psql -c "SELECT regexp_replace(version(), ',.+', '') AS version,
                          (SELECT setting FROM pg_catalog.pg_settings WHERE name = 'port') AS port,
                          current_setting('server_encoding') AS encoding,
                          (SELECT datcollate FROM pg_database WHERE datname = current_database()) AS locale"
          # Fail if values wrong.
          set -x
          psql -c "SELECT version()" | grep 'PostgreSQL ${{ matrix.pg }}'
          psql -c "SELECT setting FROM pg_catalog.pg_settings WHERE name = 'port'" | grep '${{ matrix.opt.port }}'
          psql -c "SELECT current_setting('server_encoding')" | grep '${{ matrix.opt.encoding }}'
          psql -c "SELECT datcollate FROM pg_database WHERE datname = current_database()" | grep '${{ matrix.opt.locale }}'
          pgxn --version # Always installed
          hugo version # Added by packages

  no-start:
    strategy:
      fail-fast: false
      matrix:
        os:
          - { img: 🍎, name: macOS  }
          - { img: 🐧, name: Ubuntu }
          - { img: 🪟, name: Windows  }
    name: ${{ matrix.os.img }} ${{ matrix.os.name }} no-start
    runs-on: ${{ matrix.os.name }}-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v7
      - name: Start Postgres
        id: pg
        uses: ./
        with: { version: 18, start: false }
      - name: Check Not Running
        run: if psql -c 'SELECT version()'; then printf 'Server running but should not\n'; exit 1; fi
